name: Build VC:MP 0.1c on Windows

on:
  push:
    branches:
      - main  # Replace with your default branch name if different
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Step 1: Checkout the repository (including the pre-downloaded RakNet library)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up MSBuild
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 3: Modify RakNet files
      - name: Modify RakNet files
        run: |
          # Add enum IDs to PacketEnumerations.h
          Add-Content -Path "raknet\Source\PacketEnumerations.h" -Value "`nID_PLAYER_SYNC,`nID_VEHICLE_SYNC,`nID_PASSENGER_SYNC,`nID_RCON_COMMAND,`nID_RCON_RESPONSE"

          # Add #pragma pack(1) to NetworkTypes.h
          $networkTypesPath = "raknet\Source\NetworkTypes.h"
          $content = Get-Content -Path $networkTypesPath
          $content = "#pragma pack(1)`n" + $content
          Set-Content -Path $networkTypesPath -Value $content

      # Step 4: Compile the project
      - name: Compile VC:MP
        run: |
          msbuild vcmp.sln /p:Configuration=Release /p:Platform=Win32

      # Step 5: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vcmp-build
          path: |
            path\to\output\vcmp.flt
            path\to\output\server.exe
            path\to\output\rcon.exe
