name: Build VC:MP 0.1c on Windows

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Visual Studio Build Tools
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 3: Install RakNet (if not included in the repo)
      # If RakNet is already in the repo, skip this step.
      - name: Download RakNet
        run: |
          Invoke-WebRequest -Uri "http://www.rakkarsoft.com/raknet/downloads/RakNet.zip" -OutFile "RakNet.zip"
          Expand-Archive -Path "RakNet.zip" -DestinationPath "raknet" -Force

      # Step 4: Modify RakNet files (add enum IDs and #pragma pack(1))
      - name: Modify RakNet files
        run: |
          # Add enum IDs to PacketEnumerations.h
          Add-Content -Path "raknet\Source\PacketEnumerations.h" -Value "`nID_PLAYER_SYNC,`nID_VEHICLE_SYNC,`nID_PASSENGER_SYNC,`nID_RCON_COMMAND,`nID_RCON_RESPONSE"

          # Add #pragma pack(1) to NetworkTypes.h
          $networkTypesPath = "raknet\Source\NetworkTypes.h"
          $content = Get-Content -Path $networkTypesPath
          $content = "#pragma pack(1)`n" + $content
          Set-Content -Path $networkTypesPath -Value $content

      # Step 5: Compile the project using MSBuild
      - name: Compile VC:MP
        run: |
          msbuild vcmp.sln /p:Configuration=Release /p:Platform=Win32

      # Step 6: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vcmp-build
          path: |
            path\to\output\vcmp.flt
            path\to\output\server.exe
            path\to\output\rcon.exe
